/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/blender_logo/blenderlogo.gltf 
Author: shahrukh7587 (https://sketchfab.com/shahrukh7587)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blender-logo-f4105cc7de434f2cbbc3b3d12343bb8f
Title: Blender Logo
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blenderlogo.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.473, -1.563, -2.357]} rotation={[Math.PI / 2, 0, 0]} scale={4.11}>
          <mesh geometry={nodes.Curve001_0.geometry} material={materials['SVGMat.002']} />
          <mesh geometry={nodes.Curve001_1.geometry} material={materials['SVGMat.003']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/blenderlogo.gltf')
